### ISSUE TITLE
What should I do if the .sh file doesn't run?

### ISSUE THREAD

**Issue by dydtjr1128** [MPSec/MPSec#17]
What should I do if the .sh file doesn't run?
![image](https://user-images.githubusercontent.com/19161231/53086167-e906d500-3547-11e9-8e1e-d9047c897979.png)

**Comment by wnsgml972** [comment]
Please modify permissions to use shell script!

### Example
~~~bash
chmod 777 * 
~~~

**Comment by dydtjr1128** [comment]
Thank you so much
